name: Build & test

on: [push, pull_request]
jobs:
  build-and-test:
    # Skip job based on the commit message, only works in push to branches for now
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build & test Docker images with random user
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        use-random-user: [false, true]
    steps:
      - uses: actions/checkout@v1
      - name: Output Docker info
        run: docker info
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Get branch name (only for push to branch)
        if: github.event_name == 'push'
        run: echo "::set-env name=BRANCH::$(echo ${PUSH_BRANCH##*/})"
        env:
          PUSH_BRANCH: ${{ github.ref }}
      - name: Get target branch name (only for PRs)
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH::$(echo ${TARGET_BRANCH##*/})"
        env:
          TARGET_BRANCH: ${{ github.head_ref }}
      - name: Output branch name
        run: echo ${BRANCH}
      - name: Sets build date
        run: echo ::set-env name=BUILD_DATE::$(date '+%Y%m%d')
      - name: Build Docker images
        run: VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} make build
      - name: Test Docker images
        run: USE_RANDOM_USER_ID=${USE_RANDOM_USER} VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} make test
        env:
          USE_RANDOM_USER: ${{ matrix.use-random-user }}

